require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/community_reccomendations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CommunityReccomendation. As you add validations to CommunityReccomendation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CommunityReccomendation.create! valid_attributes
      get community_reccomendations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      community_reccomendation = CommunityReccomendation.create! valid_attributes
      get community_reccomendation_url(community_reccomendation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_community_reccomendation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      community_reccomendation = CommunityReccomendation.create! valid_attributes
      get edit_community_reccomendation_url(community_reccomendation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CommunityReccomendation" do
        expect {
          post community_reccomendations_url, params: { community_reccomendation: valid_attributes }
        }.to change(CommunityReccomendation, :count).by(1)
      end

      it "redirects to the created community_reccomendation" do
        post community_reccomendations_url, params: { community_reccomendation: valid_attributes }
        expect(response).to redirect_to(community_reccomendation_url(CommunityReccomendation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CommunityReccomendation" do
        expect {
          post community_reccomendations_url, params: { community_reccomendation: invalid_attributes }
        }.to change(CommunityReccomendation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post community_reccomendations_url, params: { community_reccomendation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested community_reccomendation" do
        community_reccomendation = CommunityReccomendation.create! valid_attributes
        patch community_reccomendation_url(community_reccomendation), params: { community_reccomendation: new_attributes }
        community_reccomendation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the community_reccomendation" do
        community_reccomendation = CommunityReccomendation.create! valid_attributes
        patch community_reccomendation_url(community_reccomendation), params: { community_reccomendation: new_attributes }
        community_reccomendation.reload
        expect(response).to redirect_to(community_reccomendation_url(community_reccomendation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        community_reccomendation = CommunityReccomendation.create! valid_attributes
        patch community_reccomendation_url(community_reccomendation), params: { community_reccomendation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested community_reccomendation" do
      community_reccomendation = CommunityReccomendation.create! valid_attributes
      expect {
        delete community_reccomendation_url(community_reccomendation)
      }.to change(CommunityReccomendation, :count).by(-1)
    end

    it "redirects to the community_reccomendations list" do
      community_reccomendation = CommunityReccomendation.create! valid_attributes
      delete community_reccomendation_url(community_reccomendation)
      expect(response).to redirect_to(community_reccomendations_url)
    end
  end
end
