require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/community_reccomendations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CommunityReccomendation. As you add validations to CommunityReccomendation, be sure to
  # adjust the attributes here as well
  current_user = User.new(email: "daniele@example.com",password: "password",id:1,uid:"1");
  before(:example) do
    current_user = User.create(email: "daniele@example.com",password: "password",id:1,uid:"1");
    rock=create(:tag,name: 'Rock',id:1)
    pop=create(:tag,name: 'Pop',id:2)
    metal=create(:tag,name: 'Metal',id:3)
    create(:tag,name: 'Indie',id:4)
    create(:tag,name: 'Classica',id:5)
    create(:tag,name: 'Rap',id:6)
    create(:tag,name: 'Electro',id:7)

    TaggableUser.create(user: current_user, tag: rock)
    TaggableUser.create(user: current_user, tag: pop)
    TaggableUser.create(user: current_user, tag: metal)
    sign_in current_user
  end
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

=begin   describe "GET /index" do
    it "renders a successful response" do
      CommunityReccomendation.create! valid_attributes
      get community_reccomendations_url
      expect(response).to be_successful
    end
  end 
=end


=begin   describe "GET /edit" do
    it "renders a successful response" do
      community_reccomendation = CommunityReccomendation.create! valid_attributes
      get edit_community_reccomendation_url(community_reccomendation)
      expect(response).to be_successful
    end
  end 
=end

  describe "POST /create" do
    context "with matching commmunity (by tags 100%)" do
      
      it "creates a new CommunityReccomendation for the current user" do
        @comm=create(:community,name: "NICE", creator: "Pippo", description: "AAAAAAAAAAAAAAAA", playlist: "1mhSPC0EH13KrZrVuB441j?si=13690c7ef7254606")
        TaggableCommunity.create(community: @comm, tag_id: 1)
        TaggableCommunity.create(community: @comm, tag_id: 2)
        TaggableCommunity.create(community: @comm, tag_id: 3) 
        expect {
          post community_reccomendations_url
        }.to change(CommunityReccomendation.where(user: current_user), :count).by(1)
      end

      it "redirects to the reccomendation page" do
        @comm=create(:community,name: "NICE", creator: "Pippo", description: "AAAAAAAAAAAAAAAA", playlist: "1mhSPC0EH13KrZrVuB441j?si=13690c7ef7254606")
        TaggableCommunity.create(community: @comm, tag_id: 1)
        TaggableCommunity.create(community: @comm, tag_id: 2)
        TaggableCommunity.create(community: @comm, tag_id: 3) 

        post community_reccomendations_url
        expect(response).to redirect_to(reccomendations_path)
      end
    end
    context "with no matching commmunity (by tags 60%)" do
      it "doesn't create a new CommunityReccomendation for the current user" do
        @comm=create(:community,name: "NICE", creator: "Pippo", description: "AAAAAAAAAAAAAAAA", playlist: "1mhSPC0EH13KrZrVuB441j?si=13690c7ef7254606")
        TaggableCommunity.create(community: @comm, tag_id: 1)
        TaggableCommunity.create(community: @comm, tag_id: 2)
        TaggableCommunity.create(community: @comm, tag_id: 3)
        TaggableCommunity.create(community: @comm, tag_id: 4)
        TaggableCommunity.create(community: @comm, tag_id: 5)
        expect {
          post community_reccomendations_url
        }.to change(CommunityReccomendation.where(user: current_user), :count).by(0)
      end
    end

    context "with no matching commmunity (by tags 20%)" do
      it "doesn't create a new CommunityReccomendation for the current user" do
        @comm=create(:community,name: "NICE", creator: "Pippo", description: "AAAAAAAAAAAAAAAA", playlist: "1mhSPC0EH13KrZrVuB441j?si=13690c7ef7254606")
        TaggableCommunity.create(community: @comm, tag_id: 1)
        TaggableCommunity.create(community: @comm, tag_id: 6)
        TaggableCommunity.create(community: @comm, tag_id: 7)
        TaggableCommunity.create(community: @comm, tag_id: 4)
        TaggableCommunity.create(community: @comm, tag_id: 5)
        expect {
          post community_reccomendations_url
        }.to change(CommunityReccomendation.where(user: current_user), :count).by(0)
      end

      it "redirects to the reccomendation page" do
        @comm=create(:community,name: "NICE", creator: "Pippo", description: "AAAAAAAAAAAAAAAA", playlist: "1mhSPC0EH13KrZrVuB441j?si=13690c7ef7254606")
        TaggableCommunity.create(community: @comm, tag_id: 1)
        TaggableCommunity.create(community: @comm, tag_id: 6)
        TaggableCommunity.create(community: @comm, tag_id: 7)
        TaggableCommunity.create(community: @comm, tag_id: 4)
        TaggableCommunity.create(community: @comm, tag_id: 5)
        post community_reccomendations_url
        expect(response).to redirect_to(reccomendations_path)
      end
    end
    context "with matching commmunity (by tags 60% with 1 following)" do  
      it "creates a new CommunityReccomendation for the current user" do
        @comm=create(:community,name: "NICE", creator: "Pippo", description: "AAAAAAAAAAAAAAAA", playlist: "1mhSPC0EH13KrZrVuB441j?si=13690c7ef7254606")
        TaggableCommunity.create(community: @comm, tag_id: 1)
        TaggableCommunity.create(community: @comm, tag_id: 2)
        TaggableCommunity.create(community: @comm, tag_id: 3)
        TaggableCommunity.create(community: @comm, tag_id: 4)
        TaggableCommunity.create(community: @comm, tag_id: 5)

        user2=create(:user, id: 2,uid: '2')
        
        Follow.create(follower:current_user,followed_user:user2)
        
        Participation.create(user: user2, community: @comm)
        expect {
          post community_reccomendations_url
        }.to change(CommunityReccomendation.where(user: current_user), :count).by(1)
      end
    end
    context "with no matching commmunity (by tags 50% with 1 following)" do
    
      it "doesn't create a new CommunityReccomendation for the current user" do
        @comm=create(:community,name: "NICE", creator: "Pippo", description: "AAAAAAAAAAAAAAAA", playlist: "1mhSPC0EH13KrZrVuB441j?si=13690c7ef7254606")
        TaggableCommunity.create(community: @comm, tag_id: 1)
        TaggableCommunity.create(community: @comm, tag_id: 2)
        TaggableCommunity.create(community: @comm, tag_id: 4)
        TaggableCommunity.create(community: @comm, tag_id: 5)

        user2=create(:user, id: 2,uid: '2')
        
        Follow.create(follower:current_user,followed_user:user2)
        
        Participation.create(user: user2, community: @comm)
        expect {
          post community_reccomendations_url
        }.to change(CommunityReccomendation.where(user: current_user), :count).by(0)
      end

    end
    context "with matching commmunity (by tags 50% with 2 following)" do
      
      it "creates a new CommunityReccomendation for the current user" do
        @comm=create(:community,name: "NICE", creator: "Pippo", description: "AAAAAAAAAAAAAAAA", playlist: "1mhSPC0EH13KrZrVuB441j?si=13690c7ef7254606")
        TaggableCommunity.create(community: @comm, tag_id: 1)
        TaggableCommunity.create(community: @comm, tag_id: 2)
        TaggableCommunity.create(community: @comm, tag_id: 4)
        TaggableCommunity.create(community: @comm, tag_id: 5)

        user2=create(:user, id: 2,uid: '2')
        Follow.create(follower:current_user,followed_user:user2)
        Participation.create(user: user2, community: @comm)
        user3=create(:user, id: 3,uid: '3')
        Follow.create(follower:current_user,followed_user:user3)
        Participation.create(user: user3, community: @comm)
        
        expect {
          post community_reccomendations_url
        }.to change(CommunityReccomendation.where(user: current_user), :count).by(1)
      end
    end
    context "with no matching commmunity (by tags 40% with 2 following)" do
      
      it "doesn't create a new CommunityReccomendation for the current user" do
        @comm=create(:community,name: "NICE", creator: "Pippo", description: "AAAAAAAAAAAAAAAA", playlist: "1mhSPC0EH13KrZrVuB441j?si=13690c7ef7254606")
        TaggableCommunity.create(community: @comm, tag_id: 1)
        TaggableCommunity.create(community: @comm, tag_id: 2)
        TaggableCommunity.create(community: @comm, tag_id: 4)
        TaggableCommunity.create(community: @comm, tag_id: 5)
        TaggableCommunity.create(community: @comm, tag_id: 6)

        user2=create(:user, id: 2,uid: '2')
        Follow.create(follower:current_user,followed_user:user2)
        Participation.create(user: user2, community: @comm)
        user3=create(:user, id: 3,uid: '3')
        Follow.create(follower:current_user,followed_user:user3)
        Participation.create(user: user3, community: @comm)
        
        expect {
          post community_reccomendations_url
        }.to change(CommunityReccomendation.where(user: current_user), :count).by(0)
      end
    end
    context "with matching commmunity (by tags 40% with 3 following)" do
      
      it "creates a new CommunityReccomendation for the current user" do
        @comm=create(:community,name: "NICE", creator: "Pippo", description: "AAAAAAAAAAAAAAAA", playlist: "1mhSPC0EH13KrZrVuB441j?si=13690c7ef7254606")
        TaggableCommunity.create(community: @comm, tag_id: 1)
        TaggableCommunity.create(community: @comm, tag_id: 2)
        TaggableCommunity.create(community: @comm, tag_id: 4)
        TaggableCommunity.create(community: @comm, tag_id: 5)
        TaggableCommunity.create(community: @comm, tag_id: 6)

        user2=create(:user, id: 2,uid: '2')
        Follow.create(follower:current_user,followed_user:user2)
        Participation.create(user: user2, community: @comm)
        user3=create(:user, id: 3,uid: '3')
        Follow.create(follower:current_user,followed_user:user3)
        Participation.create(user: user3, community: @comm)
        user4=create(:user, id: 4,uid: '4')
        Follow.create(follower:current_user,followed_user:user4)
        Participation.create(user: user4, community: @comm)
        
        expect {
          post community_reccomendations_url
        }.to change(CommunityReccomendation.where(user: current_user), :count).by(1)
      end
    end
    context "with no matching commmunity (by tags 33% with 3 following)" do
      
      it "doesn't create a new CommunityReccomendation for the current user" do
        @comm=create(:community,name: "NICE", creator: "Pippo", description: "AAAAAAAAAAAAAAAA", playlist: "1mhSPC0EH13KrZrVuB441j?si=13690c7ef7354606")
        TaggableCommunity.create(community: @comm, tag_id: 1)
        TaggableCommunity.create(community: @comm, tag_id: 2)
        TaggableCommunity.create(community: @comm, tag_id: 4)
        TaggableCommunity.create(community: @comm, tag_id: 5)
        TaggableCommunity.create(community: @comm, tag_id: 6)
        TaggableCommunity.create(community: @comm, tag_id: 7)

        user2=create(:user, id: 2,uid: '2')
        Follow.create(follower:current_user,followed_user:user2)
        Participation.create(user: user2, community: @comm)
        user3=create(:user, id: 3,uid: '3')
        Follow.create(follower:current_user,followed_user:user3)
        Participation.create(user: user3, community: @comm)
        user4=create(:user, id: 4,uid: '4')
        Follow.create(follower:current_user,followed_user:user4)
        Participation.create(user: user4, community: @comm)
        
        expect {
          post community_reccomendations_url
        }.to change(CommunityReccomendation.where(user: current_user), :count).by(0)
      end
    end
  end

=begin   describe "DELETE /destroy" do
    it "destroys the requested community_reccomendation" do
      community_reccomendation = CommunityReccomendation.create! valid_attributes
      expect {
        delete community_reccomendation_url(community_reccomendation)
      }.to change(CommunityReccomendation, :count).by(-1)
    end

    it "redirects to the community_reccomendations list" do
      community_reccomendation = CommunityReccomendation.create! valid_attributes
      delete community_reccomendation_url(community_reccomendation)
      expect(response).to redirect_to(community_reccomendations_url)
    end
  end 
=end
end
