require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_reccomendations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # UserReccomendation. As you add validations to UserReccomendation, be sure to
  # adjust the attributes here as well.
  current_user = User.new(email: "daniele@example.com",password: "password",id:1,uid:"1");
  before(:example) do
    current_user = User.create(email: "daniele@example.com",password: "password",id:1,uid:"1");
    rock=create(:tag,name: 'Rock',id:1)
    pop=create(:tag,name: 'Pop',id:2)
    metal=create(:tag,name: 'Metal',id:3)
    create(:tag,name: 'Indie',id:4)
    create(:tag,name: 'Classica',id:5)
    create(:tag,name: 'Rap',id:6)
    create(:tag,name: 'Electro',id:7)

    TaggableUser.create(user: current_user, tag: rock)
    TaggableUser.create(user: current_user, tag: pop)
    TaggableUser.create(user: current_user, tag: metal)
    sign_in current_user
  end
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

=begin   describe "GET /index" do
    it "renders a successful response" do
      UserReccomendation.create! valid_attributes
      get user_reccomendations_url
      expect(response).to be_successful
    end
  end 
=end


=begin   describe "GET /edit" do
    it "renders a successful response" do
      user_reccomendation = UserReccomendation.create! valid_attributes
      get edit_user_reccomendation_url(user_reccomendation)
      expect(response).to be_successful
    end
  end 
=end

  describe "POST /create" do
    context "with matching commmunity (by tags 100%)" do
      
      it "creates a new UserReccomendation for the current user" do
        user_target=create(:user,id:7,uid:"7")
        TaggableUser.create(user: user_target, tag_id: 1)
        TaggableUser.create(user: user_target, tag_id: 2)
        TaggableUser.create(user: user_target, tag_id: 3) 
        expect {
          post user_reccomendations_url
        }.to change(UserReccomendation.where(user: current_user), :count).by(1)
      end

      it "redirects to the reccomendation page" do
        user_target=create(:user,id:7,uid:"7")
        TaggableUser.create(user: user_target, tag_id: 1)
        TaggableUser.create(user: user_target, tag_id: 2)
        TaggableUser.create(user: user_target, tag_id: 3) 

        post user_reccomendations_url
        expect(response).to redirect_to(reccomendations_path)
      end
    end
    context "with no matching commmunity (by tags 60%)" do
      it "doesn't create a new UserReccomendation for the current user" do
        user_target=create(:user,id:7,uid:"7")
        TaggableUser.create(user: user_target, tag_id: 1)
        TaggableUser.create(user: user_target, tag_id: 2)
        TaggableUser.create(user: user_target, tag_id: 3)
        TaggableUser.create(user: user_target, tag_id: 4)
        TaggableUser.create(user: user_target, tag_id: 5)
        expect {
          post user_reccomendations_url
        }.to change(UserReccomendation.where(user: current_user), :count).by(0)
      end
    end

    context "with no matching commmunity (by tags 20%)" do
      it "doesn't create a new UserReccomendation for the current user" do
        user_target=create(:user,id:7,uid:"7")
        TaggableUser.create(user: user_target, tag_id: 1)
        TaggableUser.create(user: user_target, tag_id: 6)
        TaggableUser.create(user: user_target, tag_id: 7)
        TaggableUser.create(user: user_target, tag_id: 4)
        TaggableUser.create(user: user_target, tag_id: 5)
        expect {
          post user_reccomendations_url
        }.to change(UserReccomendation.where(user: current_user), :count).by(0)
      end

      it "redirects to the reccomendation page" do
        user_target=create(:user,id:7,uid:"7")
        TaggableUser.create(user: user_target, tag_id: 1)
        TaggableUser.create(user: user_target, tag_id: 6)
        TaggableUser.create(user: user_target, tag_id: 7)
        TaggableUser.create(user: user_target, tag_id: 4)
        TaggableUser.create(user: user_target, tag_id: 5)
        post user_reccomendations_url
        expect(response).to redirect_to(reccomendations_path)
      end
    end
    context "with matching commmunity (by tags 60% with 1 following)" do  
      it "creates a new UserReccomendation for the current user" do
        user_target=create(:user,id:7,uid:"7")
        TaggableUser.create(user: user_target, tag_id: 1)
        TaggableUser.create(user: user_target, tag_id: 2)
        TaggableUser.create(user: user_target, tag_id: 3)
        TaggableUser.create(user: user_target, tag_id: 4)
        TaggableUser.create(user: user_target, tag_id: 5)

        user2=create(:user, id: 2,uid: '2')
        
        Follow.create(follower:current_user,followed_user:user2)
        
        Follow.create(follower: user2, followed_user: user_target)
        expect {
          post user_reccomendations_url
        }.to change(UserReccomendation.where(user: current_user), :count).by(1)
      end
    end
    context "with no matching commmunity (by tags 50% with 1 following)" do
    
      it "doesn't create a new UserReccomendation for the current user" do
        user_target=create(:user,id:7,uid:"7")
        TaggableUser.create(user: user_target, tag_id: 1)
        TaggableUser.create(user: user_target, tag_id: 2)
        TaggableUser.create(user: user_target, tag_id: 4)
        TaggableUser.create(user: user_target, tag_id: 5)

        user2=create(:user, id: 2,uid: '2')
        
        Follow.create(follower:current_user,followed_user:user2)
        
        Follow.create(follower: user2, followed_user: user_target)
        expect {
          post user_reccomendations_url
        }.to change(UserReccomendation.where(user: current_user), :count).by(0)
      end

    end
    context "with matching commmunity (by tags 50% with 2 following)" do
      
      it "creates a new UserReccomendation for the current user" do
        user_target=create(:user,id:7,uid:"7")
        TaggableUser.create(user: user_target, tag_id: 1)
        TaggableUser.create(user: user_target, tag_id: 2)
        TaggableUser.create(user: user_target, tag_id: 4)
        TaggableUser.create(user: user_target, tag_id: 5)

        user2=create(:user, id: 2,uid: '2')
        Follow.create(follower:current_user,followed_user:user2)
        Follow.create(follower: user2, followed_user: user_target)
        user3=create(:user, id: 3,uid: '3')
        Follow.create(follower:current_user,followed_user:user3)
        Follow.create(follower: user3, followed_user: user_target)
        
        expect {
          post user_reccomendations_url
        }.to change(UserReccomendation.where(user: current_user), :count).by(1)
      end
    end
    context "with no matching commmunity (by tags 40% with 2 following)" do
      
      it "doesn't create a new UserReccomendation for the current user" do
        user_target=create(:user,id:7,uid:"7")
        TaggableUser.create(user: user_target, tag_id: 1)
        TaggableUser.create(user: user_target, tag_id: 2)
        TaggableUser.create(user: user_target, tag_id: 4)
        TaggableUser.create(user: user_target, tag_id: 5)
        TaggableUser.create(user: user_target, tag_id: 6)

        user2=create(:user, id: 2,uid: '2')
        Follow.create(follower:current_user,followed_user:user2)
        Follow.create(follower: user2, followed_user: user_target)
        user3=create(:user, id: 3,uid: '3')
        Follow.create(follower:current_user,followed_user:user3)
        Follow.create(follower: user3, followed_user: user_target)
        
        expect {
          post user_reccomendations_url
        }.to change(UserReccomendation.where(user: current_user), :count).by(0)
      end
    end
    context "with matching commmunity (by tags 40% with 3 following)" do
      
      it "creates a new UserReccomendation for the current user" do
        user_target=create(:user,id:7,uid:"7")
        TaggableUser.create(user: user_target, tag_id: 1)
        TaggableUser.create(user: user_target, tag_id: 2)
        TaggableUser.create(user: user_target, tag_id: 4)
        TaggableUser.create(user: user_target, tag_id: 5)
        TaggableUser.create(user: user_target, tag_id: 6)

        user2=create(:user, id: 2,uid: '2')
        Follow.create(follower:current_user,followed_user:user2)
        Follow.create(follower: user2, followed_user: user_target)
        user3=create(:user, id: 3,uid: '3')
        Follow.create(follower:current_user,followed_user:user3)
        Follow.create(follower: user3, followed_user: user_target)
        user4=create(:user, id: 4,uid: '4')
        Follow.create(follower:current_user,followed_user:user4)
        Follow.create(follower: user4,followed_user: user_target)
        
        expect {
          post user_reccomendations_url
        }.to change(UserReccomendation.where(user: current_user), :count).by(1)
      end
    end
    context "with no matching commmunity (by tags 33% with 3 following)" do
      
      it "doesn't create a new UserReccomendation for the current user" do
        user_target=create(:user,id:7,uid:"7")
        TaggableUser.create(user: user_target, tag_id: 1)
        TaggableUser.create(user: user_target, tag_id: 2)
        TaggableUser.create(user: user_target, tag_id: 4)
        TaggableUser.create(user: user_target, tag_id: 5)
        TaggableUser.create(user: user_target, tag_id: 6)
        TaggableUser.create(user: user_target, tag_id: 7)

        user2=create(:user, id: 2,uid: '2')
        Follow.create(follower:current_user,followed_user:user2)
        Follow.create(follower: user2, followed_user: user_target)
        user3=create(:user, id: 3,uid: '3')
        Follow.create(follower:current_user,followed_user:user3)
        Follow.create(follower: user3, followed_user: user_target)
        user4=create(:user, id: 4,uid: '4')
        Follow.create(follower:current_user,followed_user:user4)
        Follow.create(follower: user4,followed_user: user_target)
        
        expect {
          post user_reccomendations_url
        }.to change(UserReccomendation.where(user: current_user), :count).by(0)
      end
    end
  end
end
